import 'package:shader_app/app/gen/assets.gen.dart';
import 'package:shader_app/app/models/shader_model.dart';

final shaderList = <ShaderModel>[
  ShaderModel(
    id: 'wave',
    title: 'Seascape',
    category: 'PROCEDURAL / NOISE',
    author: 'TDM',
    thumbnail: Assets.thumbnails.seascape,
    path: '/wave',
  ),
  ShaderModel(
    id: 'pyramid-fractal',
    title: 'Pyramid Fractal',
    category: 'FRACTAL / CINE SHADER',
    author: 'bradjamesgrant',
    thumbnail: Assets.thumbnails.pyramidFractal,
    path: '/pyramid-fractal',
  ),
  ShaderModel(
    id: 'water-ripple',
    title: 'Water Ripple',
    category: 'SIMULATION / WATER',
    author: 'Me',
    thumbnail: Assets.thumbnails.waterRipple,
    path: '/water-ripple',
  ),
  ShaderModel(
    id: 'ripple-effect',
    title: 'Ripple Effect',
    category: 'SIMULATION / IMAGE',
    author: 'Me',
    thumbnail: Assets.thumbnails.rippleEffect,
    path: '/ripple-effect',
  ),
  ShaderModel(
    id: 'ripple-touch',
    title: 'Ripple Touch',
    category: 'INTERACTIVE / NEW',
    author: 'touch_dev',
    thumbnail: Assets.thumbnails.rippleTouch,
    path: '/ripple-touch',
  ),
  ShaderModel(
    id: 'gradient-flow',
    title: 'Gradient Flow',
    category: 'FEATURED / NEW',
    author: 'Me',
    thumbnail: Assets.thumbnails.gradientFlow,
    path: '/gradient-flow',
  ),
  ShaderModel(
    id: 'wavy-stripes',
    title: 'Wavy Stripes',
    category: 'SINE / POLAR ANGLE',
    author: 'pattern_pro',
    thumbnail: Assets.thumbnails.wavyStripes,
    path: '/wavy-stripes',
  ),
  ShaderModel(
    id: 'burn-effect',
    title: 'Burn Effect',
    category: 'EFFECTS / POPULAR',
    author: 'Me',
    thumbnail: Assets.thumbnails.burnEffect,
    path: '/burn-effect',
  ),
  ShaderModel(
    id: 'warp-effect',
    title: 'Warp Effect',
    category: 'DISTORTION / POPULAR',
    author: 'Me',
    thumbnail: Assets.thumbnails.warpEffect,
    path: '/warp-effect',
  ),
  ShaderModel(
    id: 'plasma-effect',
    title: 'Plasma Effect',
    category: 'PLASMA / GOLF',
    author: 'Xor',
    thumbnail: Assets.thumbnails.plasmaEffect,
    path: '/plasma-effect',
  ),
  ShaderModel(
    id: 'sun-vortex',
    title: 'Sun Vortex',
    category: 'RAY-MARCHING / ABSTRACT',
    author: 'workingclasshacker',
    thumbnail: Assets.thumbnails.sunVortex,
    path: '/sun-vortex',
  ),
  ShaderModel(
    id: 'dive-cloud',
    title: 'Dive Cloud',
    category: 'CLOUD / CINE SHADER',
    author: 'lise',
    thumbnail: Assets.thumbnails.diveCloud,
    path: '/dive-cloud',
  ),
  ShaderModel(
    id: 'butterfly-flock',
    title: 'Butterfly Flock',
    category: 'BUTTERFLIES / FLOC',
    author: 'kuvkar',
    thumbnail: Assets.thumbnails.butterflyFlock,
    path: '/butterfly-flock',
  ),
  ShaderModel(
    id: 'cyberspace-warehouse',
    title: 'Cyberspace Warehouse',
    category: 'GRID / HEXAGONAL',
    author: 'bitless',
    thumbnail: Assets.thumbnails.cyberspaceWarehouse,
    path: '/cyberspace-warehouse',
  ),
  ShaderModel(
    id: 'orb-effect',
    title: 'Orb Effect',
    category: 'PARTICLES / PRISMA',
    author: 'Me',
    thumbnail: Assets.thumbnails.orbEffect,
    path: '/orb-effect',
  ),
  ShaderModel(
    id: 'hail-mary',
    title: 'Hail Mary',
    category: 'PARTICLES / TRENDING',
    author: 'Me',
    thumbnail: Assets.thumbnails.hailMary,
    path: '/hail-mary',
  ),
];
